package org.ourgrid.portal.client.common.gui;

import com.extjs.gxt.ui.client.widget.ContentPanel;
import com.extjs.gxt.ui.client.widget.Window;

public class LoginHelpWindow extends Window {

	private final ContentPanel panel = new ContentPanel();
	
	public LoginHelpWindow() {
		super();
		init();
		
		createSubmitBlenderJobsHelpPanel();
		createSubmitBlenderJobsHelpText();

		this.add(panel);
	}
	
	private void createSubmitBlenderJobsHelpText() {
	    panel.addText(getHelpText());
	}

	private void init() {
		this.setSize(430, 180);  
		this.setPlain(true);  
		this.setActive(true);
		this.setBodyBorder(false);
		this.setHeaderVisible(true);
		this.setMinimizable(true);
		this.setMaximizable(false);
		this.setResizable(false);
		this.setHeading("Login Help");
		this.setClosable(true);
	}
	
	private void createSubmitBlenderJobsHelpPanel() {
		panel.setBodyBorder(false);
		panel.setBorders(false);
		panel.setAutoHeight(true);
		panel.setAutoWidth(true);
		panel.setHeaderVisible(false);
	}
	
	public void closeWindow() {
		this.setVisible(false);
//		OurGridPortal.removeWindow(this);
	}
	
	private String getHelpText(){
		
		String text = "<p><span style='font-size:10.0pt;font-family:\"Arial\"'>Welcome to the OurGrid Portal. " 
			+ "It allows you to submit Bag-of-Tasks applications to be executed in the OurGrid Community opportunistic grid. " 
			+ "The Portal also provides a data storage service where you can place your application and input files. " 
			+ "Output files generated by your jobs can also be retrieved using this user-friendly service. " 
			+ "More information on the OurGrid grid middleware, the OurGrid Community and Bag-of-Tasks applications can be obtained on the OurGrid's "
			+ "<b><a href=\"http://www.ourgrid.org/\" target=\"_blank\">official site</a></b>.</span></p>"; 

		return text;
	}
}